# Generated by Django 2.2.6 on 2019-11-17 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptName', models.CharField(max_length=100, verbose_name='Department Name')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empCode', models.CharField(max_length=50, verbose_name='Employee Code ')),
                ('empName', models.CharField(max_length=200, verbose_name='Employee Name')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectCode', models.CharField(max_length=20, verbose_name='subject Code')),
                ('subjectName', models.CharField(max_length=200, verbose_name='Subject Name')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating1', models.IntegerField(default=0)),
                ('rating2', models.IntegerField(default=0)),
                ('rating3', models.IntegerField(default=0)),
                ('rating4', models.IntegerField(default=0)),
                ('rating5', models.IntegerField(default=0)),
                ('review', models.TextField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Subject')),
            ],
            options={
                'verbose_name': 'Rating Data',
                'verbose_name_plural': 'Rating Data',
            },
        ),
        migrations.AddField(
            model_name='faculty',
            name='subjectAlloted',
            field=models.ManyToManyField(to='core.Subject'),
        ),
    ]
