# Generated by Django 2.2.6 on 2019-11-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='description',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='graduation',
            field=models.CharField(default='Hello', max_length=500, verbose_name='Educational Qualifications'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='image',
            field=models.ImageField(default='user.jpg', upload_to='photos'),
        ),
    ]
