# Generated by Django 2.2.6 on 2019-11-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191118_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='ip',
            field=models.CharField(default=192, max_length=50, verbose_name='IP Address'),
            preserve_default=False,
        ),
    ]
