# Generated by Django 2.2.6 on 2019-11-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rating_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=models.Model, to='core.Department'),
            preserve_default=False,
        ),
    ]
