# Generated by Django 2.2.6 on 2019-11-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_entrycodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrycodes',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
