# Generated by Django 2.2.6 on 2019-11-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191118_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrycodes',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Faculty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrycodes',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Subject'),
            preserve_default=False,
        ),
    ]
