# Generated by Django 2.2.6 on 2019-11-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191118_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='description',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='empCode',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='graduation',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='image',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='subjectAlloted',
        ),
        migrations.AddField(
            model_name='faculty',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=models.Model, to='core.Department'),
            preserve_default=False,
        ),
    ]
