# Generated by Django 2.2.7 on 2019-11-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191118_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrycodes',
            options={'verbose_name': 'Entry Code', 'verbose_name_plural': 'Entry Code'},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('ip', 'faculty', 'subject')},
        ),
    ]
